### ISSUE TITLE
About adding Jawg Maps

### ISSUE THREAD

**Issue by mgzjys** [rstudio/leaflet.providers#24]
Dear developers, 

Just wondering if you have any plan of adding Jawg maps into this package. Thank you very much.

**Comment by mgzjys** [comment]
I just saw there is a function in this package to get the latest provider information. Thank you.

**Comment by mgzjys** [comment]
However, I cannot update the default providers information in leaflet package using retreived new provider list. I was wondering if you could help me with this, Thank you very much.

**Comment by schloerke** [comment]
Fixed in #27
