### ISSUE TITLE
Update to leaflet-providers@2.0.0

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/leaflet.providers#32]
As of 2023-08-25, leaflet-providers 2.0.0 isn't on npm yet. When it lands, we'll need to update our package and we should do so as early as possible.

> Ian from Stadia Maps here! I'm just making the rounds of libraries with decent traffic and came across this issue. Just a heads-up that the PR to address this in leaflet-providers upstream (https://github.com/leaflet-extras/leaflet-providers/pull/520) was opened a few weeks ago but just merged recently. I can't speak for the maintainers of that package, but it sounds like the 2.0.0 release will probably go out to npm later this week.
> 
> As with the similar OpenLayers PR, it's a breaking change (instead of provider names like `Stamen.Toner`, they will now be `Stadia.StamenToner`, since we're hosting the tiles but are still branded + contain attribution to Stamen), hence the major semver bump. I'm not sure what that means for your API, but just thought I'd drop in to flag that in case you need to do something similar. Feel free to tag me if you have any questions!

_Originally posted in https://github.com/rstudio/leaflet.providers/issues/25#issuecomment-1689997694_

**Comment by gadenbuie** [comment]
@schloerke After this change, where users previously referred to `providers$StamenToner`, they will now need to use `providers$Stadia.StamenToner`.

Do you think it's worth adding aliases to `providers_data` or wherever else is required to map `StamenToner` to `Stadia.StamenToner`?

**Comment by schloerke** [comment]
> When do you pull the bandaid?

If we keep the old tile names, then I feel like it is mis-representing what is there.  I'm a fan of just doing a hard update to the latest. 

We did this in the 1.7.0 release. I don't see a problem doing it again as the provider tiles upstream do not provide alias values.
