### ISSUE TITLE
Store the supported provider information in a static htmldependency; (Restores static Rmd/Qmd support)

### ISSUE THREAD

**Issue by schloerke** [rstudio/leaflet.providers#34]
`{leaflet}` currently sets its `package.src` to `providers_loaded()$src` when `providers.src` is retrieved ([link](https://github.com/rstudio/leaflet/blob/1c06a658d7aba355f3f602ee52a8266a6a3a07a1/R/zzz.R#L15-L17)). 

It would be nice if the default providers being loaded came from a static htmldependency to avoid always using a temp file. This would require that `leaflet.providers` perform work similar to https://github.com/rstudio/leaflet/blob/1c06a658d7aba355f3f602ee52a8266a6a3a07a1/R/plugin-providers.R#L92-L107. 

I don't know if this means we should add a `export_html_dep()` method (or something similar) so that others could save their non-standard `{leaflet.providers}` version just as we would do internally.

If resolved, it would fix https://github.com/rstudio/leaflet/issues/732 and https://github.com/rstudio/leaflet/issues/843 (or any leaflet output in an rmarkdown / quarto document).

**Comment by gadenbuie** [comment]
After talking through this we will:

1. Move the html dependency from leaflet into leaflet.providers
2. Have leaflet.providers return a dependency that points at a static file for the default leaflet provider version, or point at the unpkg url for alternate versions.

The javascript file in the html dependency simply coordinates with leaflet to find tiles from an online tile provider; there isn't much benefit in having this file be stored locally.
